version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28
    steps:
      - run:
          name: install gradle
          command: sudo apt-get update && sudo apt-get install gradle
      - checkout
      - run:
          name: build
          command: gradle assembleRelease
      - run:
          name: test
          command: "find . -name *.apk"
      - store_artifacts:
          path: build/outputs/apk/release/t4-launcher-release-unsigned.apk

